import { FormEvent, useState } from 'react';
import { useParams } from 'react-router-dom';
import Header from '@/components/Header';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { useSeo } from '@/hooks/useSeo';

type PageKey = 'sobre' | 'contato' | 'privacidade' | 'cookies' | 'termos' | 'politica-editorial' | 'anuncie';

const pageContent: Record<PageKey, { title: string; description: string; sections: { heading: string; body: string }[] }> = {
  sobre: { title: 'Sobre nós', description: 'Conheça a proposta do Os Mais VIP\'s.', sections: [{ heading: 'O portal', body: 'O Os Mais VIP\'s é um portal de notícias voltado à publicação de informação atualizada e conteúdo editorial organizado por categorias.' }, { heading: 'Nossa proposta', body: 'O portal busca apresentar notícias de forma clara, responsável e acessível, mantendo distinção entre conteúdo editorial e publicidade.' }, { heading: 'Compromisso', body: 'As matérias publicadas podem ser atualizadas quando novas informações relevantes estiverem disponíveis. Correções e observações podem ser encaminhadas pelo canal de contato.' }] },
  'politica-editorial': { title: 'Política Editorial', description: 'Princípios editoriais do Os Mais VIP\'s.', sections: [{ heading: 'Informação e responsabilidade', body: 'O conteúdo editorial deve ser preparado com clareza, responsabilidade e atenção às informações disponíveis no momento da publicação.' }, { heading: 'Atualizações e correções', body: 'Quando necessário, uma matéria pode ser atualizada para refletir informações novas ou corrigir dados. Solicitações de correção podem ser enviadas pelo contato institucional.' }, { heading: 'Transparência', body: 'Conteúdo patrocinado e publicidade são identificados de forma distinta do conteúdo editorial. A existência de publicidade não determina a pauta ou o conteúdo das notícias.' }, { heading: 'Critérios gerais', body: 'A publicação considera relevância pública, clareza, contexto e responsabilidade. O portal não afirma certificações, vínculos ou parcerias que não estejam formalmente informados.' }] },
  privacidade: { title: 'Política de Privacidade', description: 'Informações sobre privacidade no Os Mais VIP\'s.', sections: [{ heading: 'Dados técnicos', body: 'O portal pode processar dados técnicos necessários ao funcionamento do site, como informações de sessão e dados básicos do navegador. Não é criado um cadastro de leitores nesta etapa.' }, { heading: 'Métricas', body: 'Visualizações de notícias são registradas de forma agregada para métricas editoriais. O portal utiliza uma proteção contra contagens imediatas repetidas e não implementa rastreamento invasivo.' }, { heading: 'Publicidade', body: 'Anúncios próprios podem registrar cliques de forma agregada. Não há integração ativa com redes externas de publicidade nesta etapa.' }, { heading: 'Formulários', body: 'O formulário de contato está preparado, mas nenhum serviço de envio automático está configurado. Os dados não são enviados enquanto essa integração não estiver disponível.' }] },
  cookies: { title: 'Política de Cookies', description: 'Informações sobre cookies e armazenamento local.', sections: [{ heading: 'Cookies necessários', body: 'O sistema pode utilizar armazenamento local para manter a sessão de autenticação administrativa e evitar contagens imediatas repetidas de visualizações.' }, { heading: 'Métricas', body: 'As visualizações e cliques são tratados de forma agregada pelo sistema editorial e comercial.' }, { heading: 'Publicidade futura', body: 'Não são instalados cookies de terceiros ou scripts de redes de anúncios nesta etapa. Qualquer mudança deverá ser informada em atualização desta política.' }] },
  termos: { title: 'Termos de Uso', description: 'Termos gerais de utilização do portal.', sections: [{ heading: 'Uso do conteúdo', body: 'O conteúdo do portal deve ser utilizado de acordo com a legislação aplicável. A reprodução integral ou comercial deve respeitar os direitos correspondentes.' }, { heading: 'Responsabilidade do usuário', body: 'O usuário deve utilizar o portal de forma legítima e não tentar interferir em suas funções, dados ou áreas administrativas.' }, { heading: 'Links externos e publicidade', body: 'O portal pode apresentar links externos e publicidade identificada. Esses destinos possuem seus próprios termos e políticas.' }, { heading: 'Alterações', body: 'Estes termos podem ser atualizados para refletir mudanças no funcionamento do portal.' }] },
  anuncie: { title: 'Anuncie', description: 'Conheça os espaços comerciais preparados no portal.', sections: [{ heading: 'Espaços disponíveis', body: 'O sistema está preparado para banners na homepage, laterais, páginas de notícia, páginas de categoria e outros espaços comerciais.' }, { heading: 'Campanhas', body: 'É possível estruturar campanhas por posição, período, prioridade e identificação de conteúdo patrocinado.' }, { heading: 'Contato comercial', body: 'Para solicitar informações comerciais, utilize o canal de contato. Preços, audiência e condições não são informados nesta página porque dependem de cadastro e validação específicos.' }] },
  contato: { title: 'Contato', description: 'Entre em contato com o Os Mais VIP\'s.', sections: [{ heading: 'Fale conosco', body: 'Utilize o formulário abaixo para preparar uma mensagem institucional, editorial ou comercial. O envio automático ainda não está configurado.' }] },
};

export default function InstitutionalPage({ page: fixedPage }: { page?: PageKey }) {
  const { page: routePage = 'sobre' } = useParams();
  const page = fixedPage || routePage;
  const key = (page in pageContent ? page : 'sobre') as PageKey;
  const content = pageContent[key];
  const [submitted, setSubmitted] = useState(false);
  useSeo({ title: `${content.title} — Os Mais VIP's`, description: content.description, path: `/${key}` });

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setSubmitted(true);
  };

  return <div className="min-h-screen bg-background"><Header /><main className="container mx-auto max-w-4xl px-4 py-8"><div className="bg-card rounded-lg shadow-lg p-6 md:p-8"><h1 className="text-3xl md:text-4xl font-bold mb-4 text-foreground">{content.title}</h1><p className="text-lg text-muted-foreground mb-8">{content.description}</p><div className="space-y-8">{content.sections.map((section) => <section key={section.heading}><h2 className="text-xl font-semibold mb-2">{section.heading}</h2><p className="leading-7 text-muted-foreground">{section.body}</p></section>)}</div>{key === 'contato' && <form onSubmit={handleSubmit} className="mt-10 space-y-4 border-t border-border pt-8"><div className="space-y-2"><Label htmlFor="contact-name">Nome</Label><Input id="contact-name" name="name" required maxLength={120} /></div><div className="space-y-2"><Label htmlFor="contact-email">E-mail</Label><Input id="contact-email" name="email" type="email" required maxLength={160} /></div><div className="space-y-2"><Label htmlFor="contact-subject">Assunto</Label><Input id="contact-subject" name="subject" required maxLength={160} /></div><div className="space-y-2"><Label htmlFor="contact-message">Mensagem</Label><Textarea id="contact-message" name="message" required minLength={10} maxLength={3000} /></div><Button type="submit">Preparar mensagem</Button>{submitted && <p className="text-sm text-muted-foreground" role="status">Formulário validado. O envio automático ainda não está configurado.</p>}</form>}</div></main></div>;
}
