// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwgkqkbzpztiyvmigzcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3Z2txa2J6cHp0aXl2bWlnemNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NDg1MDgsImV4cCI6MjA2ODAyNDUwOH0.2_wGkz5bs7E6InSfRTIPpSUQYdj8tmC-gOoztOHVinA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});